databases:
  - name: microverse
    databaseName: money_trail
    user: miles09

services:
  - type: web
    name: budgettrail
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microverse
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
